### ISSUE TITLE
Persist config elements' state without message Key

### ISSUE THREAD

**Issue by ygalanter** [pebble/clay#126] opened 2016-06-28 13:23 UTC
Right now current state of elements is saved between config loads only if messaegeKey is set for the element. Sometimes selection needs to be preserved without actually being sent to the watch. For example a SELECT element with predefined color theme names. When theme is selected - individual colors are sent to the watch - not the theme value. But current theme selection needs to persist. Perhaps persist based on ID instead of messageKey?

**Comment by keegan-lillo** [comment] 2016-06-28 15:22
duplicate of https://github.com/pebble/clay/issues/116

**Closed by keegan-lillo** 2016-06-28 15:22 UTC
